org: {{cookiecutter.serverless_org}}
app: {{cookiecutter.serverless_app}}
service: {{cookiecutter.project_slug|slugify}}
variablesResolutionMode: 20210326

frameworkVersion: "3.1.1"
useDotenv: true
provider:
  name: aws
  stage: ${opt:stage}
  region: {{cookiecutter.aws_region}}
  lambdaHashingVersion: 20201221
  apiName: ${self:service}-${opt:stage}
  apiGateway:
    description: REST API ${self:service}
    metrics: true

functions: ${file(functions.yml):functions}